"""
train_ot2.py (Task 11)

PPO training for OT2GymEnv with ClearML remote execution support.

Fixes included:
- Remote workers may NOT receive CLI args. We detect CLEARML_TASK_ID and attach to the task.
- We connect args to ClearML as "cli_args" and on the worker we READ them back to overwrite defaults.
- Artifact upload shows diagnostics (no silent failures).
- Uploads checkpoints + final model + a zip of the entire run folder.
- Scalars are reported if ClearML task is available.

Added for staged training (Plan A):
- --resume_path: resume training from a saved PPO .zip
- --reset_timesteps: optional; reset SB3 timesteps counter (default keeps continuing)
- --recreate_env_each_chunk: close/recreate env between chunks (helps avoid PyBullet memory creep)

Example Stage 1:
  python training\\train_ot2.py --use_clearml --queue default ^
    --project_name "Mentor Group - Alican/Group 1" ^
    --task_name "OT2_STAGE1_T03" ^
    --run_name ot2_stage1_t03 ^
    --success_threshold 0.03 ^
    --total_timesteps 300000 ^
    --checkpoint_freq 102400 ^
    --n_steps 512 --batch_size 64 --n_epochs 5 ^
    --recreate_env_each_chunk

Example Stage 2 (resume Stage 1 final):
  python training\\train_ot2.py --use_clearml --queue default ^
    --project_name "Mentor Group - Alican/Group 1" ^
    --task_name "OT2_STAGE2_T01_RESUME" ^
    --run_name ot2_stage2_t01 ^
    --success_threshold 0.01 ^
    --total_timesteps 700000 ^
    --checkpoint_freq 102400 ^
    --n_steps 512 --batch_size 64 --n_epochs 5 ^
    --resume_path "<LOCAL_PATH_TO_STAGE1_FINAL_ZIP>" ^
    --recreate_env_each_chunk
"""

import os
import sys
import argparse
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

# -------------------------------------------------
# Ensure project root is on sys.path so "envs" imports work
# -------------------------------------------------
THIS_DIR = Path(__file__).resolve().parent          # .../Task11_RL/training
PROJECT_ROOT = THIS_DIR.parent                      # .../Task11_RL
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback
from envs.ot2_gym_wrapper import OT2GymEnv


def parse_args():
    p = argparse.ArgumentParser()

    # ----------------------------
    # ClearML (remote execution)
    # ----------------------------
    p.add_argument("--use_clearml", action="store_true", help="Enqueue training remotely via ClearML")
    p.add_argument("--project_name", type=str, default="Mentor Group - Alican/Group 1")
    p.add_argument("--task_name", type=str, default="OT2_PPO_Train")
    p.add_argument("--queue", type=str, default="default")
    p.add_argument("--docker", type=str, default="deanis/2023y2b-rl:latest")

    # ----------------------------
    # Run bookkeeping
    # ----------------------------
    p.add_argument("--run_name", type=str, default="", help="Folder name under models/. If empty, autogenerated.")
    p.add_argument("--seed", type=int, default=0)

    # ----------------------------
    # Environment
    # ----------------------------
    p.add_argument("--max_steps", type=int, default=400)
    p.add_argument(
        "--success_threshold",
        type=float,
        default=0.03,
        help="Start easier (cm-level). Tighten later for mm-level accuracy.",
    )
    p.add_argument("--action_repeat", type=int, default=5)
    p.add_argument("--render", action="store_true", help="Enable rendering (not recommended on server)")

    # ----------------------------
    # PPO hyperparameters
    # ----------------------------
    p.add_argument("--learning_rate", type=float, default=3e-4)
    p.add_argument("--batch_size", type=int, default=256)
    p.add_argument("--n_steps", type=int, default=2048)
    p.add_argument("--n_epochs", type=int, default=10)
    p.add_argument("--gamma", type=float, default=0.99)
    p.add_argument("--clip_range", type=float, default=0.2)
    p.add_argument("--ent_coef", type=float, default=0.0)

    # ----------------------------
    # Timesteps + checkpointing
    # ----------------------------
    p.add_argument("--total_timesteps", type=int, default=204_800)
    p.add_argument("--checkpoint_freq", type=int, default=10_240)

    # ----------------------------
    # Resume / staged training
    # ----------------------------
    p.add_argument("--resume_path", type=str, default="", help="Path to a PPO .zip to resume from")
    p.add_argument(
        "--reset_timesteps",
        action="store_true",
        help="If set, reset SB3 timesteps counter when resuming (default: continue).",
    )
    p.add_argument(
        "--recreate_env_each_chunk",
        action="store_true",
        help="Close/recreate env between chunks (helps avoid long-run PyBullet memory creep).",
    )

    return p.parse_args()


def round_up_to_multiple(x: int, m: int) -> int:
    x = int(x)
    m = int(m)
    return int(((x + m - 1) // m) * m)


def _cast_like(current_value: Any, new_value: Any) -> Any:
    """Cast new_value to the type of current_value where possible."""
    try:
        if isinstance(current_value, bool):
            if isinstance(new_value, str):
                return new_value.strip().lower() in ("1", "true", "yes", "y", "on")
            return bool(new_value)
        if isinstance(current_value, int):
            return int(new_value)
        if isinstance(current_value, float):
            return float(new_value)
        return new_value
    except Exception:
        return new_value


def upload_artifact(name: str, filepath: str):
    """Upload an artifact to ClearML with visible diagnostics."""
    try:
        from clearml import Task
        task = Task.current_task()
        if task is None:
            print(f"[upload_artifact] No current ClearML task. Skipping {name}.")
            return

        if not filepath:
            print(f"[upload_artifact] Empty filepath for {name}.")
            return

        if not os.path.exists(filepath):
            print(f"[upload_artifact] File not found for {name}: {filepath}")
            return

        size_mb = os.path.getsize(filepath) / (1024 * 1024)
        print(f"[upload_artifact] Uploading {name}: {filepath} ({size_mb:.2f} MB)")
        task.upload_artifact(name=name, artifact_object=filepath)

    except Exception as e:
        print(f"[upload_artifact] FAILED {name}: {e}")


def maybe_init_clearml_and_sync_args(args):
    """
    ClearML integration that works in BOTH contexts.
    """
    from clearml import Task
    running_on_worker = bool(os.environ.get("CLEARML_TASK_ID"))

    # ---- Remote worker path ----
    if running_on_worker:
        task = Task.current_task()
        if task is None:
            task = Task.init(project_name=args.project_name, task_name=args.task_name)

        cfg = task.connect(vars(args), name="cli_args")
        for k, v in cfg.items():
            if hasattr(args, k):
                setattr(args, k, _cast_like(getattr(args, k), v))
        return task

    # ---- Local enqueue path ----
    if not args.use_clearml:
        return None

    task = Task.init(project_name=args.project_name, task_name=args.task_name)
    task.connect(vars(args), name="cli_args")
    task.set_base_docker(args.docker)

    print("[ClearML] Enqueuing task to queue:", args.queue)
    task.execute_remotely(queue_name=args.queue)
    return task


class ClearMLScalarCallback(BaseCallback):
    """Reports a few useful Scalars to ClearML (if task/logger exists)."""
    def __init__(self, report_every_steps: int = 2048):
        super().__init__()
        self.report_every_steps = int(report_every_steps)
        self._logger = None
        self._ep_return = 0.0
        self._ep_returns = []
        self._successes = 0
        self._episodes = 0

    def _on_training_start(self) -> None:
        try:
            from clearml import Task
            task = Task.current_task()
            self._logger = task.get_logger() if task else None
        except Exception:
            self._logger = None

    def _on_step(self) -> bool:
        reward = float(self.locals["rewards"][0])
        self._ep_return += reward

        dones = self.locals["dones"]
        infos = self.locals["infos"]

        if bool(dones[0]):
            self._episodes += 1
            self._ep_returns.append(self._ep_return)
            if bool(infos[0].get("is_success", False)):
                self._successes += 1
            self._ep_return = 0.0

        if self._logger and (self.num_timesteps % self.report_every_steps == 0):
            window = 50
            recent = self._ep_returns[-window:] if self._ep_returns else []
            ep_rew_mean = sum(recent) / len(recent) if recent else 0.0
            success_rate = (self._successes / self._episodes) if self._episodes > 0 else 0.0
            it = int(self.num_timesteps)

            self._logger.report_scalar("rollout", "ep_rew_mean_est", ep_rew_mean, iteration=it)
            self._logger.report_scalar("rollout", "success_rate_est", success_rate, iteration=it)
            self._logger.report_scalar("time", "timesteps", it, iteration=it)

        return True


def make_env(args) -> OT2GymEnv:
    return OT2GymEnv(
        render=args.render,
        max_steps=args.max_steps,
        success_threshold=args.success_threshold,
        seed=args.seed,
        debug=False,
        action_repeat=args.action_repeat,
    )


def main():
    args = parse_args()

    print("ARGV:", sys.argv)

    if os.environ.get("CLEARML_TASK_ID"):
        args.use_clearml = True

    _ = maybe_init_clearml_and_sync_args(args)

    if not args.run_name:
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.run_name = f"ppo_ot2_{stamp}"

    rollout = int(args.n_steps)
    args.total_timesteps = round_up_to_multiple(args.total_timesteps, rollout)
    args.checkpoint_freq = round_up_to_multiple(args.checkpoint_freq, rollout)

    model_root = os.path.join(str(PROJECT_ROOT), "models", args.run_name)
    os.makedirs(model_root, exist_ok=True)

    total = int(args.total_timesteps)
    chunk = int(args.checkpoint_freq) if int(args.checkpoint_freq) > 0 else total

    print("\n========== TRAINING CONFIG ==========")
    print("Running remotely (CLEARML_TASK_ID set):", bool(os.environ.get("CLEARML_TASK_ID")))
    print("ClearML enabled:", bool(args.use_clearml))
    print("Project:", args.project_name)
    print("Task name:", args.task_name)
    print("Queue:", args.queue)
    print("Run name:", args.run_name)
    print("Total timesteps (rounded):", total)
    print("Checkpoint freq (rounded):", chunk)
    print("PPO n_steps:", args.n_steps)
    print("Batch size:", args.batch_size)
    print("Env max_steps:", args.max_steps)
    print("Env success_threshold:", args.success_threshold)
    print("Env action_repeat:", args.action_repeat)
    print("Resume path:", args.resume_path if args.resume_path else "(none)")
    print("Recreate env each chunk:", bool(args.recreate_env_each_chunk))
    print("Save dir:", model_root)
    print("====================================\n")

    env = make_env(args)

    if args.resume_path:
        if not os.path.exists(args.resume_path):
            raise FileNotFoundError(f"--resume_path not found: {args.resume_path}")
        print("Resuming from:", args.resume_path)
        model = PPO.load(args.resume_path, env=env, device="auto")
    else:
        model = PPO(
            "MlpPolicy",
            env,
            verbose=1,
            learning_rate=args.learning_rate,
            batch_size=args.batch_size,
            n_steps=args.n_steps,
            n_epochs=args.n_epochs,
            gamma=args.gamma,
            clip_range=args.clip_range,
            ent_coef=args.ent_coef,
        )

    cb = ClearMLScalarCallback(report_every_steps=args.n_steps)

    trained = 0
    use_progress_bar = not bool(args.use_clearml)

    while trained < total:
        this_chunk = min(chunk, total - trained)

        model.learn(
            total_timesteps=this_chunk,
            progress_bar=use_progress_bar,
            reset_num_timesteps=bool(args.reset_timesteps),
            callback=cb,
        )

        # After first call, never reset again
        args.reset_timesteps = False

        trained += this_chunk

        ckpt_base = os.path.join(model_root, f"ppo_ot2_{trained}_steps")
        ckpt_zip = f"{ckpt_base}.zip"
        print("Saving checkpoint to:", ckpt_base)
        model.save(ckpt_base)

        print("Checkpoint exists?", os.path.exists(ckpt_zip), ckpt_zip)
        upload_artifact(name=f"ppo_checkpoint_{trained}_steps", filepath=ckpt_zip)

        # Optional: recreate env between chunks to avoid long-run sim memory creep
        if args.recreate_env_each_chunk:
            try:
                env.close()
            except Exception:
                pass
            env = make_env(args)
            model.set_env(env)

    final_base = os.path.join(model_root, "ppo_ot2_final")
    final_zip = f"{final_base}.zip"
    print("Saving final model to:", final_base)
    model.save(final_base)

    print("Final model exists?", os.path.exists(final_zip), final_zip)
    upload_artifact(name="ppo_final_model", filepath=final_zip)

    try:
        zip_base = os.path.join(str(PROJECT_ROOT), "models", args.run_name)
        zip_file = shutil.make_archive(base_name=zip_base, format="zip", root_dir=model_root)
        print("Run folder zip exists?", os.path.exists(zip_file), zip_file)
        upload_artifact(name="run_folder_zip", filepath=zip_file)
    except Exception as e:
        print("[zip] FAILED:", e)

    env.close()

    print("\nTraining finished successfully.")
    print("All checkpoints saved under:", model_root)
    print("Download from ClearML: Task -> Artifacts")


if __name__ == "__main__":
    main()
