"""
train_ot2.py (Task 11)

PPO training for OT2GymEnv with ClearML remote execution support.

Features / fixes:
- Prevent ClearML recursion: local machine enqueues and exits; worker never enqueues.
- Sync CLI args via ClearML config (cli_args), because workers might not receive sys.argv.
- resume_path supports LOCAL PATH or HTTP(S) URL (ClearML artifact URL). URLs are downloaded on worker.
- Upload checkpoints + final model + run folder zip to ClearML Artifacts (with diagnostics).
- Report useful scalars to ClearML.

Recommended for long runs:
- --recreate_env_each_chunk to reduce PyBullet memory creep
"""

from __future__ import annotations

import os
import sys
import argparse
import shutil
import urllib.request
from urllib.parse import urlparse
from datetime import datetime
from pathlib import Path
from typing import Any

# -------------------------------------------------
# Ensure project root is on sys.path so "envs" imports work
# -------------------------------------------------
THIS_DIR = Path(__file__).resolve().parent          # .../Task11_RL/training
PROJECT_ROOT = THIS_DIR.parent                      # .../Task11_RL
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback
from envs.ot2_gym_wrapper import OT2GymEnv


def parse_args():
    p = argparse.ArgumentParser()

    # ----------------------------
    # ClearML (remote execution)
    # ----------------------------
    p.add_argument("--use_clearml", action="store_true", help="Enqueue training remotely via ClearML")
    p.add_argument("--project_name", type=str, default="Mentor Group - Alican/Group 1")
    p.add_argument("--task_name", type=str, default="OT2_PPO_Train")
    p.add_argument("--queue", type=str, default="default")
    p.add_argument("--docker", type=str, default="deanis/2023y2b-rl:latest")

    # ----------------------------
    # Run bookkeeping
    # ----------------------------
    p.add_argument("--run_name", type=str, default="", help="Folder name under models/. If empty, autogenerated.")
    p.add_argument("--seed", type=int, default=0)

    # ----------------------------
    # Environment
    # ----------------------------
    p.add_argument("--max_steps", type=int, default=400)
    p.add_argument("--success_threshold", type=float, default=0.03)
    p.add_argument("--action_repeat", type=int, default=5)
    p.add_argument("--render", action="store_true", help="Enable rendering (not recommended on server)")

    # ----------------------------
    # PPO hyperparameters
    # ----------------------------
    p.add_argument("--learning_rate", type=float, default=3e-4)
    p.add_argument("--batch_size", type=int, default=256)
    p.add_argument("--n_steps", type=int, default=2048)
    p.add_argument("--n_epochs", type=int, default=10)
    p.add_argument("--gamma", type=float, default=0.99)
    p.add_argument("--clip_range", type=float, default=0.2)
    p.add_argument("--ent_coef", type=float, default=0.0)

    # ----------------------------
    # Timesteps + checkpointing
    # ----------------------------
    p.add_argument("--total_timesteps", type=int, default=204_800)
    p.add_argument("--checkpoint_freq", type=int, default=10_240)

    # ----------------------------
    # Resume / staged training
    # ----------------------------
    p.add_argument(
        "--resume_path",
        type=str,
        default="",
        help="Path to PPO .zip to resume from (LOCAL PATH or HTTP(S) URL).",
    )
    p.add_argument(
        "--reset_timesteps",
        action="store_true",
        help="Reset SB3 timesteps counter when starting/resuming (default: continue).",
    )
    p.add_argument(
        "--recreate_env_each_chunk",
        action="store_true",
        help="Close/recreate env between chunks (helps avoid long-run PyBullet memory creep).",
    )

    return p.parse_args()


def round_up_to_multiple(x: int, m: int) -> int:
    x = int(x)
    m = int(m)
    return int(((x + m - 1) // m) * m)


def _cast_like(current_value: Any, new_value: Any) -> Any:
    try:
        if isinstance(current_value, bool):
            if isinstance(new_value, str):
                return new_value.strip().lower() in ("1", "true", "yes", "y", "on")
            return bool(new_value)
        if isinstance(current_value, int):
            return int(new_value)
        if isinstance(current_value, float):
            return float(new_value)
        return new_value
    except Exception:
        return new_value


def upload_artifact(name: str, filepath: str):
    """Upload an artifact to ClearML with visible diagnostics."""
    try:
        from clearml import Task
        task = Task.current_task()
        if task is None:
            print(f"[upload_artifact] No current ClearML task. Skipping {name}.")
            return

        if not filepath:
            print(f"[upload_artifact] Empty filepath for {name}.")
            return

        if not os.path.exists(filepath):
            print(f"[upload_artifact] File not found for {name}: {filepath}")
            return

        size_mb = os.path.getsize(filepath) / (1024 * 1024)
        print(f"[upload_artifact] Uploading {name}: {filepath} ({size_mb:.2f} MB)")
        task.upload_artifact(name=name, artifact_object=filepath)

    except Exception as e:
        print(f"[upload_artifact] FAILED {name}: {e}")


def maybe_download_resume(resume_path: str) -> str:
    """
    If resume_path is an http(s) URL (e.g., ClearML artifact URL),
    download it into PROJECT_ROOT/pretrained/ and return the local path.
    Otherwise return resume_path unchanged.
    """
    if not resume_path:
        return resume_path

    if resume_path.startswith("http://") or resume_path.startswith("https://"):
        dl_dir = os.path.join(str(PROJECT_ROOT), "pretrained")
        os.makedirs(dl_dir, exist_ok=True)

        parsed = urlparse(resume_path)
        filename = os.path.basename(parsed.path) or "resume_model.zip"
        local_path = os.path.join(dl_dir, filename)

        print("[resume] Detected URL. Downloading resume model...")
        print("[resume] URL:", resume_path)
        print("[resume] Local:", local_path)

        try:
            urllib.request.urlretrieve(resume_path, local_path)
        except Exception as e:
            raise RuntimeError(f"[resume] Download failed from URL:\n{resume_path}\nError: {e}")

        print("[resume] Downloaded:", os.path.exists(local_path), local_path)
        return local_path

    return resume_path


def clearml_setup(args) -> None:
    """
    Prevent recursion:
    - If on worker (CLEARML_TASK_ID set): attach to task and sync args from ClearML.
    - If local and --use_clearml: create task, connect args, enqueue, then EXIT immediately.
    - If local and not --use_clearml: do nothing.
    """
    from clearml import Task

    running_on_worker = bool(os.environ.get("CLEARML_TASK_ID"))

    if running_on_worker:
        # Worker: attach + sync args
        task = Task.current_task()
        if task is None:
            task = Task.init(project_name=args.project_name, task_name=args.task_name)

        cfg = task.connect(vars(args), name="cli_args")
        for k, v in cfg.items():
            if hasattr(args, k):
                setattr(args, k, _cast_like(getattr(args, k), v))
        return

    # Local machine:
    if not args.use_clearml:
        return

    task = Task.init(project_name=args.project_name, task_name=args.task_name)
    task.connect(vars(args), name="cli_args")
    task.set_base_docker(args.docker)

    print("[ClearML] Enqueuing task to queue:", args.queue)
    task.execute_remotely(queue_name=args.queue)

    # IMPORTANT: stop local execution to avoid double-run / recursion
    sys.exit(0)


class ClearMLScalarCallback(BaseCallback):
    """Reports a few useful Scalars to ClearML (if task/logger exists)."""
    def __init__(self, report_every_steps: int = 2048):
        super().__init__()
        self.report_every_steps = int(report_every_steps)
        self._logger = None
        self._ep_return = 0.0
        self._ep_returns = []
        self._successes = 0
        self._episodes = 0

    def _on_training_start(self) -> None:
        try:
            from clearml import Task
            task = Task.current_task()
            self._logger = task.get_logger() if task else None
        except Exception:
            self._logger = None

    def _on_step(self) -> bool:
        reward = float(self.locals["rewards"][0])
        self._ep_return += reward

        dones = self.locals["dones"]
        infos = self.locals["infos"]

        if bool(dones[0]):
            self._episodes += 1
            self._ep_returns.append(self._ep_return)
            if bool(infos[0].get("is_success", False)):
                self._successes += 1
            self._ep_return = 0.0

        if self._logger and (self.num_timesteps % self.report_every_steps == 0):
            window = 50
            recent = self._ep_returns[-window:] if self._ep_returns else []
            ep_rew_mean = sum(recent) / len(recent) if recent else 0.0
            success_rate = (self._successes / self._episodes) if self._episodes > 0 else 0.0
            it = int(self.num_timesteps)

            self._logger.report_scalar("rollout", "ep_rew_mean_est", ep_rew_mean, iteration=it)
            self._logger.report_scalar("rollout", "success_rate_est", success_rate, iteration=it)
            self._logger.report_scalar("time", "timesteps", it, iteration=it)

        return True


def make_env(args) -> OT2GymEnv:
    return OT2GymEnv(
        render=args.render,
        max_steps=args.max_steps,
        success_threshold=args.success_threshold,
        seed=args.seed,
        debug=False,
        action_repeat=args.action_repeat,
    )


def main():
    args = parse_args()

    # Always print argv (helps verify worker vs local)
    print("ARGV:", sys.argv)

    # ClearML setup:
    # - local: enqueues + exits
    # - worker: syncs args and continues
    clearml_setup(args)

    # Auto-generate run folder name if missing
    if not args.run_name:
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.run_name = f"ppo_ot2_{stamp}"

    # Align timesteps to PPO rollout size
    rollout = int(args.n_steps)
    args.total_timesteps = round_up_to_multiple(args.total_timesteps, rollout)
    args.checkpoint_freq = round_up_to_multiple(args.checkpoint_freq, rollout)

    # Model save folder
    model_root = os.path.join(str(PROJECT_ROOT), "models", args.run_name)
    os.makedirs(model_root, exist_ok=True)

    total = int(args.total_timesteps)
    chunk = int(args.checkpoint_freq) if int(args.checkpoint_freq) > 0 else total

    print("\n========== TRAINING CONFIG ==========")
    print("Running remotely (CLEARML_TASK_ID set):", bool(os.environ.get("CLEARML_TASK_ID")))
    print("ClearML enabled (flag):", bool(args.use_clearml))
    print("Project:", args.project_name)
    print("Task name:", args.task_name)
    print("Queue:", args.queue)
    print("Run name:", args.run_name)
    print("Total timesteps (rounded):", total)
    print("Checkpoint freq (rounded):", chunk)
    print("PPO n_steps:", args.n_steps)
    print("Batch size:", args.batch_size)
    print("Env max_steps:", args.max_steps)
    print("Env success_threshold:", args.success_threshold)
    print("Env action_repeat:", args.action_repeat)
    print("Resume path:", args.resume_path if args.resume_path else "(none)")
    print("Recreate env each chunk:", bool(args.recreate_env_each_chunk))
    print("Save dir:", model_root)
    print("====================================\n")

    env = make_env(args)

    # Download resume model if URL
    args.resume_path = maybe_download_resume(args.resume_path)

    if args.resume_path:
        if not os.path.exists(args.resume_path):
            raise FileNotFoundError(f"--resume_path not found: {args.resume_path}")
        print("Resuming from:", args.resume_path)
        model = PPO.load(args.resume_path, env=env, device="auto")
    else:
        model = PPO(
            "MlpPolicy",
            env,
            verbose=1,
            learning_rate=args.learning_rate,
            batch_size=args.batch_size,
            n_steps=args.n_steps,
            n_epochs=args.n_epochs,
            gamma=args.gamma,
            clip_range=args.clip_range,
            ent_coef=args.ent_coef,
        )

    cb = ClearMLScalarCallback(report_every_steps=args.n_steps)

    trained = 0
    # Keep worker logs cleaner; progress bar only locally
    use_progress_bar = not bool(os.environ.get("CLEARML_TASK_ID"))

    while trained < total:
        this_chunk = min(chunk, total - trained)

        model.learn(
            total_timesteps=this_chunk,
            progress_bar=use_progress_bar,
            reset_num_timesteps=bool(args.reset_timesteps),
            callback=cb,
        )

        # After first learn call, never reset again
        args.reset_timesteps = False

        trained += this_chunk

        ckpt_base = os.path.join(model_root, f"ppo_ot2_{trained}_steps")
        ckpt_zip = f"{ckpt_base}.zip"
        print("Saving checkpoint to:", ckpt_base)
        model.save(ckpt_base)

        print("Checkpoint exists?", os.path.exists(ckpt_zip), ckpt_zip)
        upload_artifact(name=f"ppo_checkpoint_{trained}_steps", filepath=ckpt_zip)

        # Optional: recreate env between chunks
        if args.recreate_env_each_chunk:
            try:
                env.close()
            except Exception:
                pass
            env = make_env(args)
            model.set_env(env)

    final_base = os.path.join(model_root, "ppo_ot2_final")
    final_zip = f"{final_base}.zip"
    print("Saving final model to:", final_base)
    model.save(final_base)

    print("Final model exists?", os.path.exists(final_zip), final_zip)
    upload_artifact(name="ppo_final_model", filepath=final_zip)

    # Zip whole run folder
    try:
        zip_base = os.path.join(str(PROJECT_ROOT), "models", args.run_name)
        zip_file = shutil.make_archive(base_name=zip_base, format="zip", root_dir=model_root)
        print("Run folder zip exists?", os.path.exists(zip_file), zip_file)
        upload_artifact(name="run_folder_zip", filepath=zip_file)
    except Exception as e:
        print("[zip] FAILED:", e)

    env.close()

    print("\nTraining finished successfully.")
    print("All checkpoints saved under:", model_root)
    print("Download from ClearML: Task -> Artifacts")


if __name__ == "__main__":
    main()
